version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.8

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test

workflows:
  version: 2
  build:
    jobs:
      - build
